spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    platform: "postgres"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  search:
    default:
      directory_provider: "filesystem"
      indexBase: "../"
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-doc"
server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:5000}