spring:
  datasource:
    url: "jdbc:postgresql://localhost:15432/dev_db"
    username: "dev_user"
    password: "dev_postgres"
    platform: "postgres"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  search:
    default:
      directory_provider: "filesystem"
      indexBase: "c:\\etc\\hiber_path\\"
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-doc"
server:
  port: 8080
  error:
    whitelabel:
      enabled: false