version: '3.3'
services:
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: 'dev_db'
            MYSQL_USER: 'dev_user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'root_password'
        ports:
          - '3306:3306'
        volumes:
          - mysql_dev_db:/var/lib/mysql
volumes:
    mysql_dev_db:
